FROM docker.io/library/debian:trixie-slim

LABEL maintainer="Matir <matir@@users.noreply.github.com>"

RUN apt-get update && \
  DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
  zsh git vim
